# Generated by Django 6.0.1 on 2026-02-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
    ]
