# Generated by Django 6.0.1 on 2026-02-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_author_comment_comment_remove_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
